spring:
  application:
    name: springmvc
  # .env import
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://127.0.0.1:33306/springmvc
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false